version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: auth-postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: auth

  cassandra:
    image: cassandra:latest
    container_name: cassandra-tweets
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_CLUSTER_NAME= tweets
  neo4j:
    image: neo4j:latest
    container_name: neo4j-connections
    ports:
      - "7474:7474"
      - "7687:7687"
      - "7473:7473"
    environment:
      - NEO4J_AUTH=neo4j/admin12345