version: '3.9'

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra-tweets
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_CLUSTER_NAME= tweets
  neo4j:
    image: neo4j:latest
    container_name: neo4j-connections
    ports:
      - "7474:7474"
      - "7687:7687"
      - "7473:7473"
    environment:
      - NEO4J_AUTH=neo4j/admin12345