services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j-connections
    ports:
      - "7474:7474"
      - "7687:7687"
      - "7473:7473"
    environment:
      - NEO4J_AUTH=neo4j/admin12345